export declare function validateDomainDefinition(domain: any): boolean;
export declare function createDomainState(domain: any): {
    version: string;
    values: {};
    rows: any;
    generated: any[];
    updatedAt: string;
};
export declare function calculateDomain(domain: any, state: any): {
    primary: number;
    secondary: number;
    completeness: number;
    rowScore: number;
    approved: any;
    insight: string;
    releaseReady: boolean;
};
export declare function generateDomainArtifacts(config: any, domain: any, state: any): any;
export declare function buildDomainMarkdown(config: any, domain: any, state: any): string;
export declare function applyDomainSample(domain: any): {
    version: string;
    values: {};
    rows: any;
    generated: any[];
    updatedAt: string;
};
export declare function createSaasBlueprint(domain: any, state: any): {
    stage: string;
    health: number;
    primaryContact: any;
    completedRows: any;
    approvedRows: any;
    riskRows: any;
    modules: any[];
    playbooks: any;
    automations: any;
    customerSegments: any[];
    pricingTiers: any[];
    onboardingChecklist: any[];
    successMetrics: any[];
    dashboards: any[];
    dataModel: any[];
    permissions: any[];
    compliance: any[];
    lifecycle: any[];
    retentionSignals: any[];
    exportChannels: any[];
    nextMilestones: string[];
    revenueModel: any;
    integrationTargets: any;
    riskRegister: any;
};
export declare function buildSaasMarkdown(config: any, domain: any, state: any): string;
